---
- hosts: es-masters
  remote_user: root
  sudo: yes
  tasks:
    - name: remove gcj java
      yum: name=java-gcj state=absent

    - name: install latest version of openjdk java
      yum: name=java-openjdk state=latest
      environment:
        http_proxy: http://wwwcache.rl.ac.uk:8080/
        https_proxy: http://wwwcache.rl.ac.uk:8080/

    - name: download elasticseach gpg key
      get_url: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
               dest=/tmp/GPG-KEY-elasticsearch
               use_proxy=yes
      environment:
        http_proxy: http://wwwcache.rl.ac.uk:8080/
        https_proxy: http://wwwcache.rl.ac.uk:8080/

    - name: add elasticsearch gpg key to rpm
      rpm_key: state=present key=/tmp/GPG-KEY-elasticsearch

    - name: add elasticsearch repository to yum
      copy: src=files/yum/elasticsearch.repo
            dest=/etc/yum.repos.d/elasticsearch.repo
            owner=root group=root mode=0644

    - name: install latest version of elasticsearch
      yum: pkg=elasticsearch state=latest enablerepo=elasticsearch-1.3
      environment:
        http_proxy: http://wwwcache.rl.ac.uk:8080/
        https_proxy: http://wwwcache.rl.ac.uk:8080/
      notify:
          - restart elasticsearch

    - name: template elasticsearch configuration file
      template: src=templates/elasticsearch/es.yml.j2
                dest=/etc/elasticsearch/elasticsearch.yml
      notify:
        - restart elasticsearch

    - name: calculate amount of memory to use for elasticsearch
      command: "expr {{ansible_memtotal_mb}} / 2"
      register: half_mem

    - name: template elasticsearch system defaults file
      template: src=templates/sysconfig/es.j2
                dest=/etc/sysconfig/elasticsearch
      notify:
        - restart elasticsearch

    - name: install elasticsearch-head plugin
      command: "/usr/share/elasticsearch/bin/plugin -DproxyPort=8080 -DproxyHost='wwwcache.rl.ac.uk' --install mobz/elasticsearch-head"
      register: elasticsearch_head_installed
      changed_when: elasticsearch_head_installed.rc != 74
      ignore_errors: yes
    
    - name: install bigdesk plugin
      command: "/usr/share/elasticsearch/bin/plugin -DproxyPort=8080 -DproxyHost='wwwcache.rl.ac.uk' --install lukas-vlcek/bigdesk"
      register: bigdesk_installed
      changed_when: bigdesk_installed.rc != 74
      ignore_errors: yes

    - name: backup iptables configuration to /tmp
      shell: "cp /etc/sysconfig/iptables /tmp/iptables.backup.$(date +%s)"

    - name: allow elasticsearch ports through iptables
      command: "/sbin/iptables -A INPUT -p tcp -m tcp --dport 9200:9400 -j ACCEPT"

    - name: make iptables configuration persistent
      shell: "/sbin/iptables-save > /etc/sysconfig/iptables"
      notify:
        - restart iptables

  handlers:
    - name: restart elasticsearch
      service: name=elasticsearch state=restarted
    - name: restart iptables
      service: name=iptables state=restarted
